---
output:
  pdf_document: default
  html_document: default
---
# About 
While writting this notes one gets to experiment and tinker with the Rmarkdown syntatix and the bookdown capabilities. While one tries different stuff like writting equation, adding images, videos or animations one learn some of tricks. The following is a colletion of ilustratibe examples of the syntatix needed.

## Code chuncks 
These are to in order to insert a piece of code, in Rstudio they can be with key shortcut  __control + alt + i__ in windows. they have many parameters that can determine the way they behave.

chunck headers

* ```eval=FALSE``` does not run the code
* ```include=FALSE``` The code is run but neither the output nor the are shown in the document
* ```echo=FALSE``` Prevents the code but not the results to be shown
* ```warning=FALSE``` Prevents warning from appearing
* ```fig.cap = "..."``` add a caption to the figures
* ```label='my-chunk'`` adds a name to the code chunk it is important because it would be the name of figures.

fig.width=16, fig.height=6

output format ```results```
* ```asis```
* ```hold``` 

## equations


\begin{equation*} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation*}





